package jms.test;

public class Message {

	public String getNewCMMessage(String account, String mac, String speed){
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?> "
				+ "<createOrderByValueRequest xmlns=\"http://java.sun.com/products/oss/xml/ServiceActivation\">"
				+ "     <orderValue xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"mslv-sa:ASAPOrderValue\">"
				+ "          <apiClientId/>"
				+ "          <orderKey>"
				+ "               <applicationContext xmlns=\"http://java.sun.com/products/oss/xml/Common\">"
				+ "                    <factoryClass/>"
				+ "                    <url/>"
				+ "                    <systemProperties/>"
				+ "               </applicationContext>"
				+ "               <type xmlns=\"http://java.sun.com/products/oss/xml/Common\"/>"
				+ "               <primaryKey>@TestPrimaryKey</primaryKey>"
				+ "          </orderKey>"
				+ "          <priority>3</priority>"
				+ "          <requestedCompletionDate>@TestRequestedCompletionDate</requestedCompletionDate>"
				+ "          <services>"
				+ "               <item xsi:type=\"mslv-sa:ASAPService\">"
				+ "                    <serviceKey xsi:type=\"mslv-sa:ASAPServiceKey\">"
				+ "                         <applicationContext xmlns=\"http://java.sun.com/products/oss/xml/Common\">"
				+ "                              <factoryClass/>"
				+ "                              <url/>"
				+ "                              <systemProperties/>"
				+ "                         </applicationContext>"
				+ "                         <applicationDN xmlns=\"http://java.sun.com/products/oss/xml/Common\">@TestApplicationDN</applicationDN>"
				+ "                         <type xmlns=\"http://java.sun.com/products/oss/xml/Common\"/>"
				+ "                         <primaryKey>C_INCOGNITO-IPCMPS_1-0_CREATE_CLIENTCLASS</primaryKey>"
				+ "                    </serviceKey>"
				+ "                    <asdlRoute xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">TO_BE_DETERMINED</asdlRoute>"
				+ "                    <serviceValues xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">"
				+ "                         <serviceValue xsi:type=\"ASAPServiceValue\">"
				+ "                              <name>BILLING_ACCOUNT</name>"
				+ "                              <value>" + account + "</value>"
				+ "                              <type>REQUIRED_SCALAR</type>"
				+ "                         </serviceValue>"
				+ "                         <serviceValue xsi:type=\"ASAPServiceValue\">"
				+ "                              <name>CLIENTCLASS</name>"
				+ "                              <value>" + speed + "</value>"
				+ "                              <type>REQUIRED_SCALAR</type>"
				+ "                         </serviceValue>"
				+ "                         <serviceValue xsi:type=\"ASAPServiceValue\">"
				+ "                              <name>IPCMPS_NE_ID</name>"
				+ "                              <value>E_INCOGNITO-IPC-MPS_1-0_HOST</value>"
				+ "                              <type>REQUIRED_SCALAR</type>"
				+ "                         </serviceValue>"
				+ "                         <serviceValue xsi:type=\"ASAPServiceValue\">"
				+ "                              <name>MAC</name>"
				+ "                              <value>" + mac + "</value>"
				+ "                              <type>REQUIRED_SCALAR</type>"
				+ "                         </serviceValue>"
				+ "                    </serviceValues>"
				+ "               </item>"
				+ "          </services>"
				+ "          <parentKey xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">"
				+ "               <applicationContext xmlns=\"http://java.sun.com/products/oss/xml/Common\">"
				+ "                    <factoryClass/>"
				+ "                    <url/>"
				+ "                    <systemProperties/>"
				+ "               </applicationContext>"
				+ "               <applicationDN xmlns=\"http://java.sun.com/products/oss/xml/Common\"/>"
				+ "               <type xmlns=\"http://java.sun.com/products/oss/xml/Common\"/>"
				+ "               <primaryKey xmlns=\"http://java.sun.com/products/oss/xml/ServiceActivation\"/>"
				+ "          </parentKey>"
				+ "          <origin xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">STUDIO Test Orders</origin>"
				+ "          <organizationUnit xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">STUDIO</organizationUnit>"
				+ "          <timeout xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">30</timeout>"
				+ "          <secureData xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">true</secureData>"
				+ "          <maximumDelayFail xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">0</maximumDelayFail>"
				+ "          <rollbackIfFail xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">false</rollbackIfFail>"
				+ "          <batchGroup xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\"/>"
				+ "          <asdlTimeout xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">-1</asdlTimeout>"
				+ "          <asdlRetry xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">5</asdlRetry>"
				+ "          <asdlRetryInterval xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">120</asdlRetryInterval>"
				+ "          <asdlDelayFail xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">false</asdlDelayFail>"
				+ "          <externalSystemId xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\"/>"
				+ "          <srqAction xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">ADD</srqAction>"
				+ "          <command xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\">UPDATE</command>"
				+ "          <orderParameters xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\"/>"
				+ "          <extendedWoProperties xmlns=\"http://www.metasolv.com/oss/ServiceActivation/2003\"/>"
				+ "     </orderValue>"
				+ "</createOrderByValueRequest>"
				+ "";
	}
	
}
